### ISSUE TITLE
can not shim everything.exe

### ISSUE THREAD

**Issue by metasong** [aloneguid/win-shim#2]
shmake -i C:\App\software\everything\Everything.exe -o C:\app\\_shim\every.exe -a "%s"
and run every 3 times, the processes are like this:
![image](https://user-images.githubusercontent.com/5009757/198680086-5a037d31-43f0-4bd2-92ff-e98cdfd52ddd.png)

I can not launch everything again

**Comment by metasong** [comment]
also it seems the shim is always alive, if the application is alive

**Comment by aloneguid** [comment]
I'm not using "Everything" so can't help here. You are right, shim must stay alive in order to enforce job containment, but maybe it can be improved.

**Comment by aloneguid** [comment]
Seems like you won't contribute, closing.
